set(SRC_FILES
    AppEnd.cpp
    AppStart.cpp
    AppUpdate.cpp
    AppUtil.cpp
    Fighting.cpp
    Item.cpp
    MapManager.cpp
    NPCDialog.cpp
    Player.cpp
    Read.cpp
    ScenesManager.cpp
    ShopDialog.cpp
    Stair.cpp
    TextObject.cpp
)

set(INCLUDE_FILES
    AnimationObject.hpp
    App.hpp
    BackgroundImage.hpp
    Dialog.hpp
    Door.hpp
    Enemy.hpp
    Fighting.hpp
    Fly.hpp
    ImageObject.hpp
    Item.hpp
    ItemDialog.hpp
    MapManager.hpp
    NPC.hpp
    NPCDialog.hpp
    Player.hpp
    Road.hpp
    ScenesManager.hpp
    Shop.hpp
    ShopDialog.hpp
    Stair.hpp
    TextObject.hpp
    Thing.hpp
)

set(TEST_FILES
)
